import json,pathlib
root=pathlib.Path(__file__).resolve().parent.parent
metrics=[]
def add(key,name,question,options,group=0):
 metrics.append(dict(key=key,name=name,question=question,options=[dict(value=v,label=l,explanation=e) for v,l,e in options],group=group))
add('AV','Attack vector','Where can the attacker reach the vulnerable component?', [('N','Network','The component can be attacked remotely across a network, potentially over the internet.'),('A','Adjacent','The attacker must share a restricted network context, such as the same local subnet or Bluetooth range.'),('L','Local','The attacker needs local access or must cause a user to interact with a locally delivered payload.'),('P','Physical','The attacker must physically touch or manipulate the vulnerable system.')])
add('AC','Attack complexity','Must the attacker overcome a security measure?', [('L','Low','No special action is needed to evade or overcome a security mechanism.'),('H','High','The attacker must evade or overcome a security mechanism, such as address randomization or obtaining a target-specific secret.')])
add('AT','Attack requirements','Does success depend on a particular deployment or execution condition?', [('N','None','No particular deployment or execution condition is required for exploitation.'),('P','Present','Success depends on conditions outside the attacker’s control, such as a race or an on-path position.')])
add('PR','Privileges required','What access must the attacker already have?', [('N','None','No authenticated privileges are needed before the attack.'),('L','Low','The attacker needs basic user privileges, usually limited to their own settings or resources.'),('H','High','The attacker needs significant administrative or equivalent control before exploitation.')])
add('UI','User interaction','What must someone other than the attacker do?', [('N','None','The attack succeeds without another person taking action.'),('P','Passive','A person interacts normally with the system, such as viewing a page or receiving content; no deliberate bypass is needed.'),('A','Active','A person must take a specific conscious action, such as importing a file or overriding a warning.')])
for prefix,target in [('V','vulnerable system'),('S','subsequent system')]:
 for suffix,name,question,hi,lo in [
 ('C','Confidentiality','Can the attacker read protected information?', 'All information can be exposed, or the exposed information has a direct, serious consequence.', 'Some restricted information is exposed, but the attacker has limited control over what is revealed.'),
 ('I','Integrity','Can the attacker change protected information?', 'The attacker can change any information, or the modification has a direct, serious consequence.', 'Some information can be changed, but the scope or consequences are limited.'),
 ('A','Availability','Can the attacker interrupt access to the system?', 'Access can be fully denied, or the disruption has a direct, serious consequence.', 'Performance or access is reduced, but the system remains at least partially available.')]:
  add(prefix+suffix,name+' · '+target,question+' Assess the '+target+'.',[('H','High',hi),('L','Low',lo),('N','None','There is no '+name.lower()+' impact on the '+target+'.')])
add('E','Exploit maturity','What evidence of exploitation exists?', [('X','Not defined','No threat assessment is supplied. Scoring assumes the most severe value: Attacked.'),('A','Attacked','Attacks have been reported, or usable tools exist that simplify exploitation.'),('P','Proof of concept','A proof of concept is available, but attacks have not been reported and practical exploitation tools are not known.'),('U','Unreported','No public proof of concept or attacks are known after considering available intelligence.')],1)
for key,name in [('CR','Confidentiality requirement'),('IR','Integrity requirement'),('AR','Availability requirement')]:
 add(key,name,'How important is this security property in your environment?', [('X','Not defined','No local requirement is supplied. Scoring assumes High.'),('H','High','Losing this property would have a catastrophic adverse effect on the organization or people.'),('M','Medium','Losing this property would have a serious adverse effect.'),('L','Low','Losing this property would have a limited adverse effect.')],2)
base=metrics[:11]
for m in base:
 options=[('X','Use base','Use the corresponding Base metric. No environmental override is applied.')]+[(o['value'],o['label'],o['explanation']) for o in m['options']]
 if m['key'] in ('SI','SA'):options.append(('S','Safety','An impact on human safety is possible in this environment, including serious injury or worse.'))
 add('M'+m['key'],'Modified '+m['name'].lower(),'Assess this metric for your deployment. '+m['question'],options,2)
add('S','Safety','Could exploitation affect human safety?', [('X','Not defined','No safety assessment is supplied.'),('N','Negligible','No material human safety consequence is expected.'),('P','Present','Human safety consequences are possible. This supplemental value does not change the score.')],3)
add('AU','Automatable','Can an attacker automate the full attack chain?', [('X','Not defined','Automation has not been assessed.'),('N','No','The attacker cannot reliably automate reconnaissance, weaponization, delivery, and exploitation.'),('Y','Yes','The full attack chain can be automated across multiple targets.')],3)
add('R','Recovery','How does the system recover after an attack?', [('X','Not defined','Recovery has not been assessed.'),('A','Automatic','The system recovers automatically without user or administrator intervention.'),('U','User','A user or administrator must intervene to restore operation.'),('I','Irrecoverable','Recovery is not possible through normal restoration; replacement or rebuilding is needed.')],3)
add('V','Value density','How concentrated is the value exposed by an attack?', [('X','Not defined','Value concentration has not been assessed.'),('D','Diffuse','The affected component holds relatively little value per successful attack.'),('C','Concentrated','A single successful attack gives access to a significant concentration of resources or value.')],3)
add('RE','Response effort','How much effort does initial response require?', [('X','Not defined','Response effort has not been assessed.'),('L','Low','Initial response needs little effort or resources.'),('M','Moderate','Initial response needs some substantial effort or resources.'),('H','High','Initial response needs significant, extensive effort or resources.')],3)
add('U','Provider urgency','What urgency has the vulnerability provider communicated? These labels are provider-defined, not standardized deadlines or CVSS severity bands.', [('X','Not defined','No provider urgency is supplied.'),('Clear','Clear','The provider assigns the Clear urgency designation.'),('Green','Green','The provider assigns the Green urgency designation.'),('Amber','Amber','The provider assigns the Amber urgency designation.'),('Red','Red','The provider assigns the Red urgency designation.')],3)
(root/'metrics.json').write_text(json.dumps(metrics,indent=2,ensure_ascii=False))
s='// Plain-language metric guidance. See README for the authoritative specification.\nstatic METRICS:&[Metric]=&[\n'
for m in metrics:
 s+='Metric { key:'+json.dumps(m['key'])+',name:'+json.dumps(m['name'],ensure_ascii=False)+',question:'+json.dumps(m['question'],ensure_ascii=False)+',group:'+str(m['group'])+',options:&['
 for o in m['options']:s+='OptionDef {value:'+json.dumps(o['value'])+',label:'+json.dumps(o['label'])+',explanation:'+json.dumps(o['explanation'],ensure_ascii=False)+'},'
 s+=']},\n'
s+='];\n';(root/'src/metrics.rs').write_text(s)
