/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareBindings worker/bindings.d.ts` (hash: 1c87b5d469557b5fa640b43a83b2ae40)
interface __BaseEnv_CloudflareBindings {
  OAUTH_KV: KVNamespace;
  ASSETS: Fetcher;
  ALLOW_PUBLIC_MCP: 'false';
  PUBLIC_URL: 'https://quietscore.cancun.workers.dev';
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./index');
  }
  interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, 'ALLOW_PUBLIC_MCP' | 'PUBLIC_URL'>
  > {}
}
